services:
  config-storage-1:
    image: tdb_redis:2x-latest
    volumes:
      - ./cluster/config_storage:/tdb_redis/instances.enabled/tarantool_config_storage
    command: ["tarantool", "--name", "instance001", "--config", "instances.enabled/tarantool_config_storage/config.yaml"]
    ports:
      - "4401:4401"

  config-storage-2:
    image: tdb_redis:2x-latest
    volumes:
      - ./cluster/config_storage:/tdb_redis/instances.enabled/tarantool_config_storage
    command: ["tarantool", "--name", "instance002", "--config", "instances.enabled/tarantool_config_storage/config.yaml"]
    ports:
      - "4402:4402"

  config-storage-3:
    image: tdb_redis:2x-latest
    volumes:
      - ./cluster/config_storage:/tdb_redis/instances.enabled/tarantool_config_storage
    command: ["tarantool", "--name", "instance003", "--config", "instances.enabled/tarantool_config_storage/config.yaml"]
    ports:
      - "4403:4403"

  init:
    image: tdb_redis:2x-latest
    volumes:
      - ./cluster/tdbredis:/tdb_redis/instances.enabled/tdbredis
      - ./init.sh:/init.sh:ro
    entrypoint: ["/bin/bash", "/init.sh"]
    depends_on:
      - config-storage-1
      - config-storage-2
      - config-storage-3

  failover:
    image: tdb_redis:2x-latest
    volumes:
      - ./cluster/tdbredis:/tdb_redis/instances.enabled/tdbredis
    command: ["tarantool", "--failover", "--config", "instances.enabled/tdbredis/config.yaml"]
    depends_on:
      init:
        condition: service_completed_successfully

  tdbredis-1:
    image: tdb_redis:2x-latest
    volumes:
      - ./cluster/tdbredis:/tdb_redis/instances.enabled/tdbredis
    command: ["tarantool", "--name", "instance001", "--config", "instances.enabled/tdbredis/config.yaml"]
    ports:
      - "46379:6379"
      - "36379:26379"
    depends_on:
      failover:
        condition: service_started

  tdbredis-2:
    image: tdb_redis:2x-latest
    volumes:
      - ./cluster/tdbredis:/tdb_redis/instances.enabled/tdbredis
    command: ["tarantool", "--name", "instance002", "--config", "instances.enabled/tdbredis/config.yaml"]
    ports:
      - "46380:6380"
      - "36380:26380"
    depends_on:
      failover:
        condition: service_started

  tdbredis-3:
    image: tdb_redis:2x-latest
    volumes:
      - ./cluster/tdbredis:/tdb_redis/instances.enabled/tdbredis
    command: ["tarantool", "--name", "instance003", "--config", "instances.enabled/tdbredis/config.yaml"]
    ports:
      - "46381:6381"
      - "36381:26381"
    depends_on:
      failover:
        condition: service_started

  tcm-1:
    image: tarantooldb:3x-latest
    ports:
      - "8081:8081"
    volumes:
      - ./tcm.yml:/app/tarantooldb/tcm.yml
      - ../main_cluster/config.yml:/app/tarantooldb/config.yml
    command: ./tcm -c tcm.yml
